# Generated by Django 3.2.3 on 2022-05-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dazzlesapp', '0003_auto_20220512_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart_items',
            new_name='CartItem',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='my_product',
            new_name='products',
        ),
    ]
