# Generated by Django 3.2.3 on 2022-05-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dazzlesapp', '0004_auto_20220512_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='CartItem',
        ),
    ]
